### ISSUE TITLE
Root.ts2 could not be loaded

### ISSUE THREAD

**Issue by johannessteu** [johannessteu/JohannesSteu.Bootstrap.GridSystem#1]
In Neos 2.0 the autoInclude funtion expects the Root.ts2 under `resource://JohannesSteu.Bootstrap.GridSystem/Private/TypoScripts/Root.ts2`

**Comment by OwlAsh** [comment]
Funny.

I've installed the plugin and get the error:
#1347977017: Could not include TypoScript file "resource://JohannesSteu.Bootstrap.GridSystem/Private/TypoScript/Root.ts2"

Included in my Root.ts2:
include: resource://JohannesSteu.Bootstrap.GridSystem/Private/TypoScripts/Root.ts2

but didnt helped.

But it looks like fixed and the task are closed?

**Comment by johannessteu** [comment]
Hmm. Changed the Root.ts2 to resource://JohannesSteu.Bootstrap.GridSystem/Private/TypoScript/Root.ts2

Should work now for 2.0?

**Comment by OwlAsh** [comment]
I've tried - my solution was to greate both folders. (quickfix)
I will try to check it today again.

**Comment by OwlAsh** [comment]
I have today the same issue.

After the install, it searching "TypoScripts/".
When I rename the Folder to "TypoScripts/", it searching for "TypoScript/".
Never ending story.

**Comment by OwlAsh** [comment]
@johannessteu still error.
I've maked now a fork and put both folder (hotfix).
